#!/bin/sh
SCRIPTINGCLASSPATH=/Users/skelter/.m2/repository/org/clojure/clojure/1.5.1/clojure-1.5.1.jar:\
/Users/skelter/.m2/repository/clojure-jsr223/clojure-jsr223/1.2/clojure-jsr223-1.2.jar:\
target/scriptingwithclojure-1.0-SNAPSHOT.jar

java -cp $SCRIPTINGCLASSPATH org.austinclojuremeetup.scriptingwithclojure.App "$@"
